---
title: "Yifan"
author: "Hanbo Dong, Huiye Han, Yifan Lu, Zhuoran Li"
output:
  html_document:
    fig_height: 4.5
    fig_width: 8
  pdf_document:
    fig_height: 3.5
    fig_width: 3.5
  word_document:
    toc: no
---
```{r, warning = FALSE, message = FALSE}
library(tidyverse)
library(tidymodels)
library(janitor)
library(tableone)
library(here)
library(nortest)
```

```{r, warning = FALSE, message = FALSE}
load("brfss2013.RData")
brfss2013 <- clean_names(brfss2013)
# 筛选factor
factors <- tolower(c("SLEPTIM1", "X_AGE65YR", 
                     "MISHOPLS", "MISTMNT", "MISPHLPF", "MISNOWRK",
                     "SEX","X_EDUCAG", "X_INCOMG", "X_BMI5CAT","VETERAN3"))

brfss_sleep_mental <- brfss2013 %>%
  select(factors)
# head(brfss_sleep_mental)
# skimr::skim(brfss_sleep_mental)

# 删除_INCOMG的“DONT KNOW”,
# 留下internet的Yes和No
# 留下misphlpf的前五个
# 留下x_incomg的前几个
brfss_sleep_mental <- brfss_sleep_mental %>%
  filter(!x_incomg == "Don’t know/Not sure/Missing") %>%
  filter(misphlpf %in% c("Disagree strongly", 
                         "Disagree slightly", 
                         "Neither agree nor disagree", 
                         "Agree slightly",
                         "Agree strongly")) %>%
  filter(x_incomg %in% c("Less than $15,000", 
                         "$15,000 to less than $25,000", 
                         "$25,000 to less than $35,000",
                         "$35,000 to less than $50,000",
                         "$50,000 or more")) %>%
  filter(!x_educag == "9")
```

```{r}
# 整体缺失值删除
brfss_sleep_mental_omit <- na.omit(brfss_sleep_mental)
# head(brfss_sleep_mental_omit)
# skimr::skim(brfss_sleep_mental_omit)
```

```{r}
# 根据人口年龄创建adult，是否是成年人（1:成年人， 0:大于65的老年人）
brfss_sleep_mental_omit <- brfss_sleep_mental_omit %>%
  filter(x_age65yr == "Age 18 to 64")

# sex转换成数值型分类变量
brfss_sleep_mental <- brfss_sleep_mental %>%
  mutate(sex = case_when(
    sex == "Male" ~ "1", # 1:Male
    sex == "Female" ~ "0")) # 0:Female

# 睡眠评级
brfss_sleep_mental <- brfss_sleep_mental_omit %>%
  mutate(sleep_well = case_when(
    sleptim1 >= 7 & sleptim1 <= 9 ~ "1",
    sleptim1 < 7 ~ "0",
    sleptim1 > 9 ~ "0"))

# mishopls(失去希望的程度）变成数值型有序分类数据
brfss_sleep_mental <- brfss_sleep_mental %>%
  mutate(mishopls = case_when(
    mishopls == "None" ~ "0", # 0：失去希望程度最低
    mishopls == "A little" ~ "1",
    mishopls == "Some" ~ "2",
    mishopls == "Most" ~ "3",
    mishopls == "All" ~ "4")) # 4: 失去希望程度最高

# mistmnt(是否在接受治疗)
brfss_sleep_mental <- brfss_sleep_mental %>%
  mutate(mistmnt = case_when(
    mistmnt == "Yes" ~ "1", # 1：接受治疗
    mistmnt == "No" ~ "0")) # 0: 没接受治疗

# misphlpf(是否认同身边人关切同情心理疾病患者) 变成数值型有序分类数据
brfss_sleep_mental <- brfss_sleep_mental %>%
  mutate(misphlpf = case_when(
    misphlpf == "Disagree strongly" ~ "0", # 0：完全不认同身边人关切同情心理疾病患者
    misphlpf == "Disagree slightly" ~ "1",
    misphlpf == "Neither agree nor disagree" ~ "2",
    misphlpf == "Agree slightly" ~ "3",
    misphlpf == "Agree strongly" ~ "4")) 

# x_incomg (收入等级划分，调查者分好的) 变成数值型有序分类数据
brfss_sleep_mental <- brfss_sleep_mental %>%
  mutate(x_incomg = case_when(
    x_incomg == "Less than $15,000" ~ "1", # 1：收入最少
    x_incomg == "$15,000 to less than $25,000" ~ "2",
    x_incomg == "$25,000 to less than $35,000" ~ "3",
    x_incomg == "$35,000 to less than $50,000" ~ "4",
    x_incomg == "$50,000 or more" ~ "5"))   # 5: 收入最多

# x_educag(教育等级划分)变成数值型有序分类数据
brfss_sleep_mental <- brfss_sleep_mental %>%
  mutate(x_educag = case_when(
    x_educag == "Did not graduate high school" ~ "1", # 1：教育水平最低
    x_educag == "Graduated high school" ~ "2",
    x_educag == "Attended college or technical school" ~ "3",
    x_educag == "Graduated from college or technical school" ~ "4"))

# x_bmi5cat(BMI)变成数值型有序分类变量
brfss_sleep_mental <- brfss_sleep_mental %>%
  mutate(x_bmi5cat = case_when(
    x_bmi5cat == "Underweight" ~ "1", # 1：Underweight
    x_bmi5cat == "Normal Weight" ~ "2",
    x_bmi5cat == "Overweight" ~ "3",
    x_bmi5cat == "Obese" ~ "4"))

# veteran3(是否是退伍老兵)变成数值型有序分类变量
brfss_sleep_mental <- brfss_sleep_mental %>%
  mutate(veteran3 = case_when(
    veteran3 == "Yes" ~ "1", # 1：是退伍军人
    veteran3 == "No" ~ "0")) # 0: 不是退伍军人

# 删除x_age65yr列
brfss_sleep_mental <- brfss_sleep_mental %>%
  select(!x_age65yr)

# 删除x_educag列
brfss_sleep_mental <- brfss_sleep_mental %>%
  filter(!x_educag == "NA")

# convert to numeric
brfss_sleep_mental$sleptim1 <- as.numeric(brfss_sleep_mental$sleptim1)
brfss_sleep_mental$mistmnt <- as.numeric(brfss_sleep_mental$mistmnt)
brfss_sleep_mental$misphlpf <- as.numeric(brfss_sleep_mental$misphlpf)
brfss_sleep_mental$mishopls <- as.numeric(brfss_sleep_mental$mishopls)
brfss_sleep_mental$sex <- as.numeric(brfss_sleep_mental$sex)
brfss_sleep_mental$x_incomg <- as.numeric(brfss_sleep_mental$x_incomg)
brfss_sleep_mental$x_educag <- as.numeric(brfss_sleep_mental$x_educag)
brfss_sleep_mental$x_bmi5cat <- as.numeric(brfss_sleep_mental$x_bmi5cat)
brfss_sleep_mental$veteran3 <- as.numeric(brfss_sleep_mental$veteran3)

write.csv(brfss_sleep_mental,"Data_folder/brfss_sleep_mental.csv")
```



```{r}
# sleep_well 在不同性别下的分布
ggplot(brfss_sleep_mental, aes(x=factor(sleep_well), fill=factor(sex))) + 
  geom_bar(position="stack") +
  labs(title="Sleep Well Distribution by Gender", x="Sleep Well", y="Frequency") +
  scale_fill_discrete(name="Gender")
```

```{r}
mat_sex <- xtabs(~ sleep_well + sex, data = brfss_sleep_mental)
mat_sex

expected_sex <- chisq.test(mat_sex)$expected
expected_sex
```
**Two overall tests.None of the expected counts in this table is smaller than 5, so we should use X2 test statistic.**
```{r}
chisq.test(mat_sex,correct=FALSE)
chisq.test(mat_sex,correct=FALSE)$statistic %>% round(3)
```

```{r}
ggplot(brfss_sleep_mental, aes(x = misnowrk)) +
  geom_histogram(binwidth = 1, fill = "blue", color = "black", alpha = 0.7) +
  labs(title = "Histogram of misnowrk Column",
       x = "Values",
       y = "Frequency") +
  theme_minimal()
qqnorm(brfss_sleep_mental$misnowrk, main = "QQ Plot of Misnowrk", xlab = "Theoretical Quantiles", ylab = "Sample Quantiles")
qqline(brfss_sleep_mental$misnowrk, col = 2)
```